/// @description pulse_polygon_value(current_value, min_value, max_value, growing_status, pulse_magnitude)
/// @function pulse_polygon_value
/// @param current_value
/// @param min_value
/// @param max_value
/// @param growing_status
/// @param  pulse_magnitude
/// @description Linear movement between two values for a polygon generated by DrawPolygon()
    
var _current_value		= argument0;
var _min_value			= argument1;
var _max_value			= argument2;
var _growing_status		= argument3;
var _pulse_magnitude	= argument4;


// Linear pulse
if ((_current_value < _max_value) and (_growing_status == true)) {
	_current_value += _pulse_magnitude;
}
else if (_current_value == _max_value) {
	_growing_status = !_growing_status;
}

if ((_current_value > _min_value) and (_growing_status == false)) {
	_current_value -= _pulse_magnitude;
}
else if (_current_value == _min_value) {
	_growing_status = !_growing_status;
}

return_array[0] = _current_value
return_array[1] = _growing_status
return return_array